### PR TITLE
Jade dickinson show contributor name

### PR DESCRIPTION
**Pull request by svileshina**
### Why
This adds the contributor's name to a contribution -  Working off of https://github.com/rubyforgood/mutual-aid/pull/791

### What
Added the contributor name to contributions through contribution.person, so added person to the contribution blueprint and appropriate tests and supporting files 

### Next Steps
- [ ] Add a conditional so this is only displayed for logged in users with admin permissions #933
- [ ] Add the same functionality to Map View #934 

### Outstanding Questions, Concerns and Other Notes
We would like to replace raw json (i.e. lib/contributions.json) in the future

### Meta
We added Jade as a contributor because this was based on their work (https://github.com/rubyforgood/mutual-aid/pull/791) and closed their original PR that had merge conflicts 

### Pre-Merge Checklist

- [x] Security & accessibility have been considered
- [x] Tests have been added, or an explanation has been given why the features cannot be tested
- [x] Documentation and comments have been added to the codebase where required
- [ ] Entry added to CHANGELOG.md if appropriate
- [ ] Outstanding questions and concerns have been resolved
- [ ] Any next steps have been turned into Issues or Discussions as appropriate

### CODE REVIEW

**Comment by svileshina** [comment]
we are going to wait on for the "Add a conditional so this is only displayed for logged in users with admin permissions" to be done before potentially merging @maebeale

**Comment by svileshina** [comment]
Some thoughts/questions we had in trying to make this conditional: 
- we can keep pronouns (get rid of split)
- we are want to move conditional into blueprinter which requires figuring out dynamic selection of which view to render (similar "Supporting Dynamic Blueprints For Associations" of blueprinter... perhaps)
- alternative: just put the conditional and name into a presenter which then gets passed to serializer

**Comment by exbinary** [comment]
@svileshina , please take a look at my 3 most recent commits. I believe this completes the outstanding issues on this branch?

**Review by exbinary — APPROVED** [review]
Reviewed in person with @svileshina .

**Comment by svileshina** [comment]
looks great, thank you for all the work!!!

**Pull request merged**
