### PR TITLE
Issue #782 : Ruby version upgraded to 2.7.2.

### PR DESCRIPTION
**Pull request by sharvy**
### Why
To include security fix in Webrick and many [other changes](https://github.com/ruby/ruby/compare/v2_7_1...v2_7_2).
Resolves [#782](https://github.com/rubyforgood/mutual-aid/issues/782)

### How
- [x] Update Gemfile and ruby-version files
- [x] Upgraded Node to 14+ and Webpacker to 5+. 
- [x] Update Development Dockerfile & Production Dockerfile
- [x] Change CircleCI Config
- [x] Change Ansible Config 
- [x] Build locally, run tests `bin/dev/test`, make sure all Green
- [x] Make sure CircleCI is working

### Pre-Merge Checklist
- [x] Documentation and comments have been added to the codebase where required
- [x] Outstanding questions and concerns have been resolved

### CODE REVIEW

**Comment by h-m-m** [comment]
Hi, @sharvy! I'm willing to spend some time looking into the test failures, that node error message. I can think of a couple of places to start adjusting for this, though I'm not 100% what's the best fix long-term. Do you have a good feel for this yourself?

**Comment by sharvy** [comment]
@h-m-m, 

We are using node 12.x. But all the prebuilt images (Docker, CircleCI) have node 14.x with Ruby 2.7.2.

**One solution could be**: Using images with node 12. Fortunately Docker has ruby:2.7.2-alpine.3.12, but CircleCI doesn't have any prebuilt image. So we can [install nvm and swap node version in CircleCI.](https://discuss.circleci.com/t/setting-node-version-on-ruby-cimg/38130/2). I don't think that's a good solution for the long run.

**Another solution could be**: Upgrading node to 14.x in our project. Best for the long run, according to my opinion.

I went with the later solution, and everything is working perfectly.

**Comment by grenewode** [comment]
Another nice thing about doing this is that it would allow for easy use & packaging on [NixOS](https://nixos.org/), which [packages only](https://search.nixos.org/packages?channel=20.09&show=ruby_2_7&from=0&size=50&buckets=%7B%22package_attr_set%22%3A%5B%5D%2C%22package_license_set%22%3A%5B%5D%2C%22package_maintainers_set%22%3A%5B%5D%2C%22package_platforms%22%3A%5B%5D%7D&sort=relevance&query=ruby) ruby 2.7.2

**Comment by exbinary** [comment]
This looks great @sharvy 💥
I'm going to deploy your branch to http://mutual-aid-test.herokuapp.com/ just to ensure it deploys ok.
Anything else needed before we merge?

**Comment by exbinary** [comment]
Hmm, so it deploys w/o error but loading any page generates the following error:
```
2021-03-11T05:32:57.002492+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443] ActionView::Template::Error (Webpacker can't find application.css in /app/public/packs/manifest.json. Possible causes:
2021-03-11T05:32:57.002493+00:00 app[web.1]: 1. You want to set webpacker.yml value of compile to true for your environment
2021-03-11T05:32:57.002493+00:00 app[web.1]: unless you are using the `webpack -w` or the webpack-dev-server.
2021-03-11T05:32:57.002493+00:00 app[web.1]: 2. webpack has not yet re-run to reflect updates.
2021-03-11T05:32:57.002494+00:00 app[web.1]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
2021-03-11T05:32:57.002494+00:00 app[web.1]: 4. Your webpack configuration is not creating a manifest.
2021-03-11T05:32:57.002495+00:00 app[web.1]: Your manifest contains:
2021-03-11T05:32:57.002495+00:00 app[web.1]: {
2021-03-11T05:32:57.002495+00:00 app[web.1]: }
2021-03-11T05:32:57.002496+00:00 app[web.1]: ):
2021-03-11T05:32:57.002496+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443]      6:   <meta name="viewport" content="width=device-width, initial-scale=1" />
2021-03-11T05:32:57.002515+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443]      7:   <script src='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
2021-03-11T05:32:57.002516+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443]      8:
2021-03-11T05:32:57.002516+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443]      9:   <%= stylesheet_pack_tag 'application' %>
2021-03-11T05:32:57.002517+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443]     10:   <%= javascript_pack_tag 'application' %>
2021-03-11T05:32:57.002517+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443]     11: </head>
2021-03-11T05:32:57.002517+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443]
2021-03-11T05:32:57.002518+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443] app/views/layouts/_head.html.erb:9
2021-03-11T05:32:57.002518+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443] app/views/layouts/application.html.erb:3
2021-03-11T05:32:57.002525+00:00 app[web.1]: [b9e6c950-ee4f-47e4-8927-9b0e49890443] app/controllers/application_controller.rb:25:in `switch_locale'
```
Looks like possibly a webpack configuration error? Could be something broke on the `webpacker` upgrade.
I'll take a deeper look tomorrow but wanted to give you the update in the meantime.
🤔

**Comment by sharvy** [comment]
@exbinary I think I figured it out. `application.sass` was not getting compiled and `application.css` was not getting generated, since key `resolved_paths` in no more valid in Webpacker versions >= 5. I changed the key to `additional_paths` and pushed a commit. Hope it will fix the issue. Can you give it a try?

**Comment by exbinary** [comment]
@sharvy , appreciate you following up on this and good catch. Unfortunately that change itself didn't fix the issue.

Good news is i believe i've found the two necessary fixes. I have a separate PR to upgrade just `webpacker` so i've implemented the fixes [there](https://github.com/rubyforgood/mutual-aid/pull/818/commits). See the two most recent commits (8/12). That branch now seems to work on heroku.

Feel free to cherry-pick (or reimplement) those two changes into your branch. I think this'll cause less merge conflicts than merging my PR first but i'm happy to do it that way if you prefer.

Btw, for this and future troubleshooting, i was able to recreate the issue locally by running:
```shell
rm -rf public/packs
NODE_ENV=production RAILS_ENV=production bin/rails assets:precompile
```
At first, that showed the issue with `webpack-cli`. Once i upgraded that, then a compilation error surfaced which prompted the `node-fetch` addition.

**Comment by sharvy** [comment]
@exbinary I have picked the changes from your PR. 🙂 
Everything is working as expected, locally and on docker.

**Review by exbinary — APPROVED** [review]
Looks great! 💥 🙏🏾

**Pull request merged**
