### PR TITLE
Renew RuboCop effort based on StandardRB

### PR DESCRIPTION
**Pull request by exbinary**
### Why
Back in October, @smoline put in some great work introducing `rubocop` into our codebase.
Sadly, we had to prioritize feature development and weren't able to complete and merge all that work.
This is the first of several PRs intended to revive that effort.

Since then, [StandardRB](https://github.com/testdouble/standard) has hit v1.0 and i think there's a lot to gain from basing our rules on theirs. Primarily, they've done a lot of work to weigh different alternative options and tried to standardize, which means we have less to think about!

That said, StandardRB is an inherently 'opinionated' tool and (not surprisingly 😏), i would like a little more flexibility than it allows.

As such, i'm proposing that we **base** our rules on StandardRB but retain the ability to customize on top of them.

### What
In this PR:
- [x] Replace our fledgling `.rubocop.yml` config with one that inherits from StandardRB, via the `standard` gem.
- [x] Generate a `.rubocop_todo.yml` which encapsulates and excludes all existing violations. This allows us to enable linting of new code without having to first fix the whole codebase. It also sets up follow-on PRs to fix violations; see Next Steps below.
- [x] Cherry pick @smoline's 62ce3a0, which adds rubocop to our CircleCI build 💥🙏🏾

See Next Steps for a list of follow-up PRs that customize the ruleset and incrementally address existing violations.

### How
The integration with StandardRB is based on this [evilmartians.com article](https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard#one-standard-to-rule-them-all).

The idea is to continue using `rubocop` executables instead of `standard` but simply to base our rubocop config on theirs.

### Testing
Adds StandardRB-based rubocop validation to our CI builds.

### Next Steps
- [x] The following PRs build on this one to address existing violations, incrementally paring down `.rubocop_todo.yml`. Some of them also customize or override Standard rules. Most build on the previous one and can be merged independently in the order listed below.
    - [x] #936 Rules related to spaces
    - [x] #937 Indentation consistency
    - [x] #938 Alignment and Indentation
    - [x] #939 Trailing commas
    - [x] #940 Single line methods
    - [x] #941 String literals
    - [x] #942 Empty lines and trailing whitespace
    - [x] #943 Remaining style rules
    - [x] #944 Semantic blocks
    - [x] #947 Unsafe YAML.load
    - [x] #948 Linting
    - [x] #949 Metrics
- [x] Once we've addressed violations that can be auto-corrected or manually fixed relatively easily, move the remaining violations into the codebase as `# rubocop:todo` [comments](https://docs.rubocop.org/rubocop/configuration.html#disabling-cops-within-source-code) so they are more visible and likely to be addresses when we next touch related code.
- [ ] Continue to tweak our customized ruleset as we add new code.

### Outstanding Questions, Concerns and Other Notes
Would love to hear opinions about this approach of:

1. basing our ruleset on StandardRB, and
2. allowing for our own customizations (which, to be clear, is something StandardRB does _not_ recommend).

### Meta
Huge shoutout to @smoline for laying the groundwork for all this. Sorry we couldn't merge your PRs as-is, but we're very much indebted to that foundation!

### Pre-Merge Checklist
- [x] Security & accessibility have been considered
- [x] Tests have been added, or an explanation has been given why the features cannot be tested
- [x] Documentation and comments have been added to the codebase where required
- [ ] Entry added to CHANGELOG.md if appropriate
- [ ] Outstanding questions and concerns have been resolved
- [ ] Any next steps have been turned into Issues or Discussions as appropriate

### CODE REVIEW

**Comment by maebeale** [comment]
Cool idea!

**Comment by maebeale** [comment]
YES, omg, @smoline, we've been trying to figure out how to merge all that amazing work for a while now. THANK YOU for taking on such a huge task and driving the investment in linting!!!!!

**Comment by maebeale** [comment]
I do think this should make it in to changelog developer notes.

**Comment by exbinary** [comment]
@maebeale, @h-m-m, @svileshina : we chatted a bit about this last night and i _think_ i heard general agreement.

But we also ran out of time so i'd love explicit approval about this general approach before merging. I also likely won't be around tuesday morning, so if you can give it some consideration and post any thoughts, that would be great.

Could also be useful to look over a few of the follow up PRs listed under next steps above. We can review them fully over time, but they'll help paint a fuller picture of what the path towards full integration would look like.

**Comment by exbinary** [comment]
Discussed and approved in person.

**Pull request merged**
