### PR TITLE
Remove name in map view

### PR DESCRIPTION
**Pull request by AngelaGuardia**
### Why
Improving user privacy by removing person name from the contributions map view
Addresses one item in #819 

### Pre-Merge Checklist

- [x] All new features have been described in the pull request
- [x] Security & accessibility have been considered
- [ ] High quality tests have been added, or an explanation has been given why the features cannot be tested
- [x] New features have been documented, and the code is understandable and well commented
- [ ] Entry added to CHANGELOG.md if appropriate
- [ ] All outstanding questions and concerns have been resolved
- [ ] Any next steps that seem like good ideas have been created as issues for future discussion & implementation

### What
-  prevent person name from showing on map view

Before
Screen Shot 2021-02-03 at 1 54 18 PM

After
Screen Shot 2021-02-03 at 1 59 40 PM

### How
- Removed `(person.name)` from `listing.rb` `name` method

### Testing
- No tests were added for this. Tested visually.

### Outstanding Questions, Concerns and Other Notes
- The current solution may affect other views in the app where the person name is desired
- Instead of modifying the `name` method, I wanted to create a new method in `listing.rb` called `private_name` and call that on line 63 of `MapBrowser.vue`. That way I could be certain that this change would not affect other areas of the app. I wasn't able to make that work but it may be a better solution.

### CODE REVIEW

**Comment by h-m-m** [comment]
@AngelaGuardia I like a nice clean solution like this

Since this change affects the UI, can you post "before" and "after" screenshots?
Also, do you mind adding a test for this? I'm happy to help with that if our testing setup isn't one you're familiar with

**Comment by AngelaGuardia** [comment]
> @AngelaGuardia I like a nice clean solution like this
> 
> Since this change affects the UI, can you post "before" and "after" screenshots?
> Also, do you mind adding a test for this? I'm happy to help with that if our testing setup isn't one you're familiar with

@h-m-m I added the screenshots! I'm not sure how the map decides which listings to display (it usually just displays one). In this case, the one it displayed on main was different than the one on my branch but you can still see how the name is not shown anymore.

I would love to pair on adding tests! Both to this PR and the other I'm working on. I'm unfamiliar with the setup you're currently using.

**Comment by h-m-m** [comment]
Great! The screenshots look good

I'm happy to go over our testing setup with you tomorrow during the project's usual Zoom call

**Review by exbinary — APPROVED** [review]
Sweet! 🍠 🙌🏾

**Pull request merged**
